apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: ini belajar membuat pod volum
  labels:
    app: nginx-pod
  name: pod-vol
spec:
  volumes:
  - name: volume-nfs
    nfs:
      server: 172.23.9.208
      path: /mnt/peserta3
  containers:
  - image: nginx
    name: pod-vol
    volumeMounts:
      - name: volume-nfs
        mountPath: /usr/share/nginx/html
  initContainers:
  - name: build-app
    image: busybox:1.28
    command: ['sh', '-c', 'echo "build apps using init container" > /data/index.html']
    volumeMounts:
      - name: volume-nfs
        mountPath: /data
  imagePullSecrets:
    - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
