apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-test
  name: pod-test
  namespace: test
spec:
  containers:
  - image: nginx
    name: pod-nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "500m"
  imagePullSecrets:
    - name: dockerhub
  restartPolicy: Always
