apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-pvc
  name: pod-pvc
spec:
  volumes:
    - name: volume-nfs
      persistentVolumeClaim:
        claimName: pvc-a
  containers:
  - image: nginx
    name: pod-nginx
    volumeMounts:
    - name: volume-nfs
      mountPath: /usr/share/nginx/html
  imagePullSecrets:
    - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
