apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: ini belajar membuat pod sidecar
  labels:
    app: pod-sidecar
  name: pod-sidecar
spec:
  containers:
  - image: tomcat
    name: ct-tomcat
  - image: nginx
    name: ct-nginx
  imagePullSecrets:
    - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
