apiVersion: v1
kind: Pod
metadata:
  annotations:
    description: ini belajar membuat pod init
  labels:
    app: nginx-pod
  name: pod-init
spec:
  containers:
  - image: nginx
    name: main-app
    volumeMounts:
      - name: data
        mountPath: /usr/share/nginx/html/
  initContainers:
  - image: busybox:1.28
    name: build-app
    command: ['sh', '-c', 'echo "build apps using init container" > /data/index.html']
    volumeMounts:
      - name: data
        mountPath: /data
  imagePullSecrets:
    - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: data
      emptyDir: {}
