apiVersion: v1
kind: Pod
metadata:
  labels:
    apps-type: frontend
  annotations:
    description: ini belajar membuat pod
  name: pod-liveness
spec:
  containers:
  - image: nginx
    name: ct-nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
