apiVersion: v1
kind: Pod
metadata:
  labels:
    apps-type: frontend
# add this
  annotations:
    description: ini belajar membuat pod
  name: pod-readiness
spec:
  containers:
  - image: nginx
    name: ct-nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
