apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-dev
  name: pod-dev
  namespace: dev
spec:
  containers:
  - image: nginx
    name: pod-dev
  imagePullSecrets:
    - name: dockerhub
  dnsPolicy: ClusterFirst
  restartPolicy: Always
