apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx
  template:
    metadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: ct-nginx
        image: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dockerhub
