apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  description: Test deskripsi
commonLabels:
  apps: nginx
  version: dev
nameSuffix: -dev
namespace: dev
images:
- name: nginx
  newTag: 1.25.3-bookworm 
resources:
- deployment.yml
