apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-a
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: pv-a
  nfs:
    path: /mnt/peserta3
    server: 172.23.9.208
