apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-green
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx
      version: green
  template:
    metadata:
      labels:
        apps: nginx
        version: green
    spec:
      containers:
      - name: ct-nginx
        image: nginx:1.25.3-bookworm
        ports:
        - containerPort: 80
