apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx
      version: blue
  template:
    metadata:
      labels:
        apps: nginx
        version: blue
    spec:
      containers:
      - name: ct-nginx
        image: nginx:1.24-bullseye
        ports:
        - containerPort: 80
